name = "lean-modulus"
version = "0.1.0"
defaultTargets = ["lean-modulus"]

[[lean_lib]]
name = "LeanModulus"

[[lean_exe]]
name = "lean-modulus"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
