-- Formalization of "Fairest Edge Usage and Minimum Expected Overlap for Random
-- Spanning Trees" (Albin, Clemens, Hoare, Poggi-Corradini, Sit, Tymochko, 2021),
-- https://doi.org/10.1016/j.disc.2020.112282
--
-- placeholder: definitions from Section 1 (random spanning trees, MEO, FEU) to come
