-- Formalization of "Fairest Edge Usage and Minimum Expected Overlap for Random
-- Spanning Trees" (Albin, Clemens, Hoare, Poggi-Corradini, Sit, Tymochko, 2021),
-- https://arxiv.org/abs/1805.10112
--
-- placeholder: definitions from Section 1 (random spanning trees, MEO, FEU) to come
